name: flutter_webview_pro  #插件的名称，改动的时候需要注意，可能会引起插件中的引用改动，导致其他问题。
description: A Flutter plugin that provides a WebView widget on Android and iOS. # 插件描述
homepage: https://github.com/wenzhiming/flutter_webview_pro.git  #项目的git地址
version: 1.0.3 #当前插件版本，每一次发布都不能和以前版本号一样
#author: wenzhiming<313902419@qq.com> # 作者信息，会显示到 https://pub.flutter-io.cn 中

environment:
  sdk: ">=2.12.0  <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.10.0

flutter:
  plugin:
    platforms:
      android:
        package: com.wzm.webviewflutter
        pluginClass: WebViewFlutterPlugin
      ios:
        pluginClass: WebViewProFlutterPlugin
